# Generated by Django 6.0.5 on 2026-05-19 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kgco2', models.FloatField(verbose_name='Total kgCO₂eq')),
                ('total_arboles', models.FloatField(verbose_name='Árboles equivalentes')),
                ('artefactos_kgco2', models.FloatField(verbose_name='Artefactos kgCO₂eq')),
                ('clima_kgco2', models.FloatField(verbose_name='Clima kgCO₂eq')),
                ('transporte_kgco2', models.FloatField(verbose_name='Transporte kgCO₂eq')),
                ('input_data', models.JSONField(verbose_name='Datos de entrada')),
                ('detalle', models.JSONField(blank=True, default=dict, verbose_name='Detalle del cálculo')),
                ('label', models.CharField(blank=True, default='', help_text='Nombre descriptivo opcional para identificar este cálculo.', max_length=100, verbose_name='Etiqueta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de cálculo',
                'verbose_name_plural': 'registros de cálculos',
                'ordering': ['-created_at'],
            },
        ),
    ]
